version: '3'

services:
    noviti-app:
        container_name: noviti-app
        volumes:
            - ./rest-api:/var/www/symfony
        ports:
            - "8080:80"
        build:
            dockerfile: docker/app/Dockerfile

    noviti-front:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - ./front-end:/usr/share/nginx/html

    noviti-db:
        container_name: noviti-db
        image: postgres:14.3
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: noviti-db
        ports:
            - 15432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data