nelmio_cors:
  paths:
    "^/":
      allow_origin: ['http://localhost:8000', 'http://127.0.0.1:8000']
      allow_headers: ["X-Requested-With", "Content-Type", "Authorization"]
      allow_methods: ["GET", "POST"]
      max_age: 3600
